[package]
name = "attalus"
version = "0.1.0"
authors = ["Michael Benfield <mike.benfield@gmail.com>"]

[lib]
name = "attalus"
path = "src/lib.rs"

[[bin]]
name = "attalus"
path = "src/main.rs"
doc = false

[dependencies]

[dev-dependencies]
quickcheck = "0.4"

